version: '3'

services:
  nodejs:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: gustcoder/nodejs
    container_name: nodejs
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    networks:
      - node-network
networks:
  node-network:
    driver: bridge   